### ISSUE TITLE
Add to Terraform Registry

### ISSUE THREAD

**Issue by stuart-c** [form3tech-oss/terraform-provider-grafanacloud#4]
Are there plans to add this provider to the Terraform Registry to make it easier to use?

**Comment by peterbuecker-form3** [comment]
Thanks for asking @stuart-c. It looks like there is [work going on by Grafana Labs](https://github.com/grafana/terraform-provider-grafana/pull/213) themselves, so we currently don't plan to push our provider to the Terraform Registry in order to avoid confusion later on.

In the meantime I suggest you use https://github.com/hashicorp/terraform/tree/main/tools/terraform-bundle or setup a private Terraform Registry to get this up and running.
